import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/footer";
import { AuthProvider } from "@/lib/context/authContext";
import AuthGate from "@/components/login/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased sm:pt-8 bg-(--bg-main) min-h-screen flex flex-col`}>
        <Navbar />
        <AuthProvider>
          <AuthGate>
            <main className="flex-1">{children}</main>
          </AuthGate>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
